package com.epicode.GreenTravelPlanner.repositories;

import com.epicode.GreenTravelPlanner.entities.Trip;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import java.util.List;

/**
 * Repository interface for managing Trip entities.
 * Offers both derived query methods and manual JPQL queries to filter trips
 * based on titles or specific user ownership.
 */
public interface TripRepository extends JpaRepository<Trip, Long> {

    /**
     * Derived Query: Automatically generated by Spring Data JPA.
     * Finds trips where the title contains the specified string, ignoring case sensitivity.
     * * @param title the string to search for within trip titles
     * @return a list of trips matching the partial title
     */
    List<Trip> findByTitleContainingIgnoreCase(String title);

    /**
     * Manual JPQL Query: Explicitly defined using the @Query annotation.
     * Selects all trips associated with a specific owner's user ID.
     * * @param userId the unique identifier of the user who owns the trips
     * @return a list of Trip entities belonging to the specified user
     */
    @Query("SELECT t FROM Trip t WHERE t.owner.id = :userId")
    List<Trip> findAllByUserId(@Param("userId") Long userId);
}